Add P-256 and P-384 in cryptographic signatures
decentralized-identity/jwt-vc-presentation-profile pull request #69
Opened 2022-10-05 18:06 UTC by troyronda

Closes: #66

2022-10-13 18:20 UTC, quartzjer approved these changes

2022-10-14 18:03 UTC, Sakurann requested changes

2022-10-14 18:03 UTC, Sakurann commented on spec/spec.md
> +|P-384 (secp384r1)|ES384|
Suggest we make P curves optional for both verifiers and wallets.
and suggest we enhance the table as below:

|Key Type|JWT Algorithm|Mandatory/Optional for the Verifier|Mandatory/Optional for the Wallet|
|--------|-------------|---|---|
|secp256k1|ES256K|M|O*|
|Ed25519|EdDSA|M|O*|
|P-256 (secp256r1)|ES256|O|O|
|P-384 (secp384r1)|ES384|O|O|
* MUST support at least one.

2022-10-18 17:53 UTC, Sakurann commented on spec/spec.md
> +|P-384 (secp384r1)|ES384|
also this sentence should be improved "While ION supports any public key JWK representation in a DID Document, implementors of this document MUST support JWT signature verification with the following Key Types and must support JWT signing with at least one." 
to something like
"Verifiers and wallets compliant with this profile MUST support JWT signature verification of the Key Types as defined in the table below"

2022-10-19 18:35 UTC, troyronda commented
@Sakurann Updated.

2022-10-24 15:02 UTC, jischr commented on spec/spec.md
> +`C*` Conditional: MUST support at least one.
What do you think about adding that M stands for must? 
```suggestion
`C*` Conditional: MUST support at least one.
`M` Must: MUST support
```

2022-11-02 18:18 UTC, jischr approved these changes

2022-11-02 18:18 UTC, merged

2022-11-02 23:25 UTC, Sakurann commented on spec/spec.md
> +|P-384 (secp384r1)|ES384|
this change has not been addressed